//ERROR NUMS 
#define  ERR_CODE_NOT_ENOUGH_ARGUMENTS  -1
#define  ERR_CODE_TOO_MANY_ARGUMENTS  -2
#define  FAILAD_TO_OPEN_FILE -3 
#define  NOT_VALID_INPUT -4
#define  MEMORY_ALLOCATION_FAILURE -5
#define  FAILAD_TO_CLOSE_FILE -6
#define  FAILED_CREATE_PROCESS -7 
#define  SON_TERMINATING_BRUTALLY -8
#define  FAILED_WRITE_TO_FILE -9
#define  TIMEOUT_IN_MILLISECONDS 5000
#define  BRUTAL_TERMINATION_CODE 0x55


///
#define  LEN_OF_SPACE_AND_EXIT_CODE 7
#define  ADDITION_LEN_TO_PATH 3
#define  MAX_LINE_LEN  50

//#define MAX_LEN_OF_FOREST_STRING=