//ERROR NUMS 
#ifndef __HARD_CODED_DATA__ 
# define __HARD_CODED_DATA__  

typedef unsigned long int  uli;
#define TIMEOUT_IN_MILLISECONDS 5000
#define BRUTAL_TERMINATION_CODE 0x55
 

/// LENS 
#define  LEN_OF_SPACE_AND_EXIT_CODE 7
#define  ADDITION_LEN_TO_PATH 3
#define  MAX_LINE_LEN  50

enum ERRORS_ENUM {
	SUCESS,
	ERR_CODE_NOT_ENOUGH_ARGUMENTS,
	ERR_CODE_TOO_MANY_ARGUMENTS,
	FAILAD_TO_OPEN_FILE,
	NOT_VALID_INPUT,
	MEMORY_ALLOCATION_FAILURE,
	FAILAD_TO_CLOSE_FILE,
	FAILED_CREATE_PROCESS,
	SON_TERMINATING_BRUTALLY,
	FAILED_WRITE_TO_FILE,
	INVALID_INPUT_PARM_EMPTY_POINTER,
	EMPTY_FILE,
	ERROR_READ_FILE,
	ERROR_WRITE_FILE,
	NOT_A_NUMBER 
};
#endif
//#define MAX_LEN_OF_FOREST_STRING=